### ISSUE TITLE
make this webpage responsive

### ISSUE THREAD

**Issue by urzahmed** [urz-ahmed/paintApp#1]
make this webpage responsive
Things to take care before doing any changes
-> make this webpage fully mobile responsive
-> add a hamburger icon to the right of navbar

**Comment by robin6717** [comment]
Hi pagsum, can you assign me to do this? I would love that!
kind regards,
Robin

**Comment by urzahmed** [comment]
> Hi pagsum, can you assign me to do this? I would love that! kind regards, Robin

ok go for it dont use any frameworks
Just use basics
